PostgreSQL 13 support
citusdata/cstore_fdw pull request #241
Opened 2020-11-05 13:31 UTC by erma07

Modified the code to support PostgreSQL v13

2020-12-04 10:39 UTC, df7cb commented
Hi,
thanks for working on this, Debian needs a new cstore_fdw package to proceed with migrating to PG13.

Unfortunately, there's a problem in the regression tests:
```
2020-12-04 11:37:25.266 CET [326277] LOG:  server process (PID 326329) was terminated by signal 11: Segmentation fault
2020-12-04 11:37:25.266 CET [326277] DETAIL:  Failed process was running: COPY contestant FROM '/srv/projects/postgresql/cstore-fdw/cstore-fdw/data/contestants.1.csv' WITH CSV;
2020-12-04 11:37:25.266 CET [326277] LOG:  terminating any other active server processes
```

2020-12-04 15:55 UTC, erma07 commented
My bad, had no way to test pre 13 versions and regression tests here takes ages. tuptoaster.h for  <= 12 was missing. Should be working now.

2020-12-11 07:02 UTC, onlined requested changes

2020-12-11 07:02 UTC, onlined commented on Makefile
>      $(error PostgreSQL 9.3 to 12 is required to compile this extension)
```suggestion
    $(error PostgreSQL 9.3 to 13 is required to compile this extension)
```

2021-02-05 12:37 UTC, StepanYankevych commented
Guys, any estimates when PG13 support can be released? 
We plan to migrate to PG13 some on env and would be great to use cstore in PG13.

2021-02-06 09:06 UTC, pykello commented
@StepanYankevych pg13 was merged in https://github.com/citusdata/cstore_fdw/pull/243. I will close this PR.

2021-02-06 09:06 UTC, closed without merging